version: "3.6"
services:
# 
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=15432
    ports:
      - 15432:5432
# 
  game-master:
    image: jakmeier/paddlers:game-master-snapshot
    depends_on:
      - db
    ports:
      - 8088:8088
    environment:
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgresql://postgres:password@db:5432
      - DATABASE_INIT=1
      - INSERT_TEST_DATA=1
      - RUST_LOG=actix_web=debug
#
  db-interface:
    image: jakmeier/paddlers:db-interface-snapshot
    depends_on:
      - db
    ports:
      - 65432:65432
    environment:
      - RUST_BACKTRACE=1
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=65432
      - ROCKET_DATABASES={game_db={url="postgresql://postgres:password@db:5432"}}
#
  frontend:
    image: jakmeier/paddlers:frontend-snapshot
    ports:
      - 80:80
    