[package]
name = "paddlers-frontend" # To be redefined (happy duck, happy-bird, ...)
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"


[dependencies]
paddlers-shared-lib = { path = "../paddlers-shared-lib", features = ["enum_utils", "game_mechanics"] }
quicksilver = { version = "0.3", default-features = false, features = ["fonts"] }
stdweb = {version = "0.4.18", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
specs = { version = "0.15", default-features = false } # parallel not supported in wasm
specs-derive = "0.4"
graphql_client = "0.8"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
pathfinding = "1.1"

futures-preview = "0.3.0-alpha.15"
futures-util-preview = "0.3.0-alpha.17"


[features]
mobile_debug = []