[package]
name = "paddlers-frontend"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"
license = "MIT/Apache-2.0"
categories = ["wasm", "game"]


[dependencies]
paddlers-shared-lib = { path = "../paddlers-shared-lib", features = ["enum_utils", "game_mechanics"] }
panes = { git = "https://github.com/jakmeier/panes" }
# quicksilver = { version = "0.3", default-features = false, features = ["fonts", "complex_shapes"] }
quicksilver = { path = "../quicksilver", default-features = false, features = ["fonts", "complex_shapes"] }
stdweb = {version = "0.4.20", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
specs = { version = "0.15.1", default-features = false } # parallel not supported in wasm
shred = { version = "0.9.4", default-features = false }
specs-derive = "0.4"
graphql_client = "0.8"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
pathfinding = "2.0.3"
url = "2.1.0"
statistical = { version = "1.0", optional = true }

futures-preview = "0.3.0-alpha.18"
futures-util-preview = "0.3.0-alpha.18"


[features]
mobile_debug = []
dev_view = ["statistical"]