[package]
name = "integration-tests"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
workspace = ".."

edition = "2018"

[dependencies]
paddlers-db-lib = { path = "../paddlers-db-lib" }
paddlers-api-lib = { path = "../paddlers-api-lib" }
serde = "1.0"
serde_json = "1.0"
